
package introsde.soap.eactivity.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PeopleImplService", targetNamespace = "http://ws.eactivity.soap.introsde/", wsdlLocation = "http://studentactivity.herokuapp.com/ws/people?wsdl")
public class PeopleImplService
    extends Service
{

    private final static URL PEOPLEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PEOPLEIMPLSERVICE_EXCEPTION;
    private final static QName PEOPLEIMPLSERVICE_QNAME = new QName("http://ws.eactivity.soap.introsde/", "PeopleImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://studentactivity.herokuapp.com/ws/people?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PEOPLEIMPLSERVICE_WSDL_LOCATION = url;
        PEOPLEIMPLSERVICE_EXCEPTION = e;
    }

    public PeopleImplService() {
        super(__getWsdlLocation(), PEOPLEIMPLSERVICE_QNAME);
    }

    public PeopleImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PEOPLEIMPLSERVICE_QNAME, features);
    }

    public PeopleImplService(URL wsdlLocation) {
        super(wsdlLocation, PEOPLEIMPLSERVICE_QNAME);
    }

    public PeopleImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PEOPLEIMPLSERVICE_QNAME, features);
    }

    public PeopleImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PeopleImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns People
     */
    @WebEndpoint(name = "PeopleImplPort")
    public People getPeopleImplPort() {
        return super.getPort(new QName("http://ws.eactivity.soap.introsde/", "PeopleImplPort"), People.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns People
     */
    @WebEndpoint(name = "PeopleImplPort")
    public People getPeopleImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.eactivity.soap.introsde/", "PeopleImplPort"), People.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PEOPLEIMPLSERVICE_EXCEPTION!= null) {
            throw PEOPLEIMPLSERVICE_EXCEPTION;
        }
        return PEOPLEIMPLSERVICE_WSDL_LOCATION;
    }

}
